name: Deploy to EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          known-hosts: ${{ secrets.EC2_KNOWN_HOSTS }}

      - name: Copy files to EC2
        run: scp -r ./ ec2-user@SEU_IP:/home/ec2-user/SEU_PROJETO

      - name: Set environment variables
        run: |
          echo "SQLITE_PATH='./database.sqlite'" >> .env

      - name: Run deploy commands
        run: ssh ec2-user@SEU_IP "cd teste-tecnico-backend && npm install && npm run start:prod"
