name: Deploy to EC2

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}

    - name: Copy files to EC2
      run: |
        scp -i ~/.ssh/id_rsa -r ./ ec2-user@SEU_IP:/home/ec2-user/SEU_PROJETO

    - name: Set environment variables
      run: |
        echo "SQLITE_PATH='./database.sqlite'" >> .env

    - name: Run deploy commands on EC2
      run: |
        ssh -i ~/.ssh/id_rsa ec2-user@SEU_IP "cd /home/ec2-user/SEU_PROJETO && npm install && npm run start:prod"
